# Generated by Django 5.0.3 on 2024-03-25 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2activities',
            name='format',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_column='Format', default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='r2participants',
            name='person2',
            field=models.ManyToManyField(related_name='person2', to='backend.e1people'),
        ),
        migrations.AlterField(
            model_name='r1activitieslog',
            name='activity',
            field=models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e2activities', verbose_name='Activity'),
        ),
        migrations.CreateModel(
            name='R6ActivityAssign',
            fields=[
                ('activityassignid', models.AutoField(db_column='ActivityAssignID', primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e2activities')),
                ('member', models.ManyToManyField(db_column='PersonID', to='backend.e1people')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'r6_activity_assign',
            },
        ),
    ]
