# Generated by Django 5.0.3 on 2024-09-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_activitysummary_and_participantsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='R2Organisers',
            fields=[
                ('organiserid', models.AutoField(db_column='OrganisersID', primary_key=True, serialize=False)),
                ('activitieslogid', models.ForeignKey(db_column='ActivitiesLogID', default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.r1activitieslog', verbose_name='Activity')),
                ('person', models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='backend.e1people', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Organiser',
                'verbose_name_plural': 'Organisers',
                'db_table': 'r2_organisers',
                'unique_together': {('activitieslogid', 'person')},
            },
        ),
    ]
