# Generated by Django 5.0.3 on 2024-03-26 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_e2activities_format_r2participants_person2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r2participants',
            name='person2',
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='description',
            field=models.TextField(db_column='ActivityDescription', default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='person',
            field=models.ForeignKey(blank=True, db_column='PersonID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e1people', verbose_name='Person in charge'),
        ),
        migrations.RemoveField(
            model_name='r6activityassign',
            name='member',
        ),
        migrations.AddField(
            model_name='r6activityassign',
            name='member',
            field=models.ForeignKey(db_column='PersonID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e1people'),
        ),
    ]
