# Generated by Django 5.0.3 on 2024-09-28 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_activitysummary_participantsummary_r2organisers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(db_column='Level', max_length=5)),
                ('centre', models.ForeignKey(blank=True, db_column='Centre', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.e5centres')),
                ('group', models.ForeignKey(blank=True, db_column='Group', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.e4groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
