# Generated by Django 5.0.3 on 2024-08-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_memberactivities_alter_r1activitieslog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='E6Cities',
            fields=[
                ('cityid', models.AutoField(db_column='CityID', primary_key=True, serialize=False)),
                ('city', models.TextField(db_column='City', default='', verbose_name='City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AlterModelOptions(
            name='e1people',
            options={'ordering': ('surname',), 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='format',
            field=models.CharField(db_column='Format', default='1', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='e2activitytype',
            name='activityformat',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_column='ActivityFormat', default='open', max_length=10, verbose_name='Activity format'),
        ),
        migrations.AlterField(
            model_name='e2activitytype',
            name='serialnoonreport',
            field=models.IntegerField(blank=True, db_column='SerialNoOnReport', default=1, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='E5Centres',
            fields=[
                ('centreid', models.AutoField(db_column='CentreID', primary_key=True, serialize=False)),
                ('centre', models.TextField(db_column='Centre', default='', verbose_name='Centre')),
                ('city', models.ForeignKey(db_column='City', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e6cities', verbose_name='City of centre')),
            ],
            options={
                'verbose_name': 'Centre',
                'verbose_name_plural': 'Centres',
                'db_table': 'e5_centres',
            },
        ),
    ]
