# Generated by Django 5.0.3 on 2024-09-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_activitysummary_participantsummary_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='level',
            field=models.IntegerField(choices=[('0', '0'),('1', '1'),('2', '2'),('3', '3'),], db_column='Level', default=0),
        ),
    ]
