# Generated by Django 5.0.3 on 2024-08-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_e6cities_alter_e1people_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e4groups',
            name='cel',
        ),
        migrations.RemoveField(
            model_name='e4groups',
            name='egr',
        ),
        migrations.AddField(
            model_name='e4groups',
            name='centre',
            field=models.ForeignKey(db_column='Centre', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres', verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='e5centres',
            name='centre',
            field=models.CharField(db_column='Centre', default='', max_length=50, verbose_name='Name of centre'),
        ),
        migrations.CreateModel(
            name='R7PersonCentreAssign',
            fields=[
                ('centrepersonid', models.AutoField(db_column='PersonCentre', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(db_column='CentreID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres')),
                ('person', models.ForeignKey(db_column='PersonID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e1people')),
            ],
            options={
                'verbose_name': 'Centres of people',
            },
        ),
        migrations.CreateModel(
            name='R8ActivityCentreAssign',
            fields=[
                ('centrepersonid', models.AutoField(db_column='ActivityCentre', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e2activities')),
                ('centre', models.ForeignKey(db_column='CentreID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres')),
            ],
            options={
                'verbose_name': 'Centres of activiies',
            },
        ),
        migrations.CreateModel(
            name='R9GroupCentreAssign',
            fields=[
                ('centrepersonid', models.AutoField(db_column='GroupCentre', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(db_column='CentreID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres')),
                ('group', models.ForeignKey(db_column='GroupID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e4groups')),
            ],
            options={
                'verbose_name': 'Centres of activiies',
            },
        ),
    ]
