# Generated by Django 5.0.3 on 2024-11-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_activitysummary_participantsummary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='R2Organisers',
        ),
    ]
