# Generated by Django 5.0.3 on 2024-08-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_e4groups_cel_remove_e4groups_egr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e4groups',
            name='centre',
            field=models.ForeignKey(db_column='Centre', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres', verbose_name='Centre'),
        ),
    ]
