# Generated by Django 5.0.3 on 2024-08-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_e4groups_centre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e4groups',
            name='centre',
        ),
        migrations.AlterField(
            model_name='e5centres',
            name='city',
            field=models.ForeignKey(blank=True, db_column='City', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e6cities', verbose_name='City of centre'),
        ),
    ]
