# Generated by Django 5.0.3 on 2024-11-18 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_activitysummary_participantsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='R2Organisers',
            fields=[
                ('organiserid', models.AutoField(db_column='OrganisersID', primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(db_column='ActivityID', default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.e2activities', verbose_name='Activity')),
                ('person', models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='backend.e1people', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Organiser',
                'verbose_name_plural': 'Organisers',
                'db_table': 'r2_organisers',
            },
        ),
    ]
