# Generated by Django 5.0.3 on 2024-08-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_e4groups_centre_alter_e5centres_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='e4groups',
            name='centre',
            field=models.ForeignKey(db_column='Centre', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres', verbose_name='Centre'),
        ),
        migrations.AddField(
            model_name='e5centres',
            name='acronym',
            field=models.CharField(db_column='CentreAcronym', default='', max_length=50, verbose_name='Centre acronym'),
        ),
        migrations.AlterField(
            model_name='e6cities',
            name='city',
            field=models.CharField(db_column='City', default='', max_length=20, verbose_name='City'),
        ),
    ]
