# Generated by Django 5.0.3 on 2024-11-25 09:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_userstatus_options_userperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaceholders',
            fields=[
                ('placeholderid', models.AutoField(db_column='ParticipantsID', primary_key=True, serialize=False)),
                ('tempid', models.IntegerField(blank=True, db_column='TempID', null=True)),
                ('surname', models.CharField(blank=True, db_column='Surname', max_length=30, null=True, verbose_name='Surname')),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=30, null=True, verbose_name='First name')),
                ('othername', models.CharField(blank=True, db_column='OtherName', max_length=30, null=True, verbose_name='Other name(s)')),
            ],
            options={
                'verbose_name': 'User Placeholder',
            },
        ),
        migrations.AddField(
            model_name='r2participants',
            name='entrydate',
            field=models.DateTimeField(blank=True, db_column='Entry Date', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='r2participants',
            name='entryperson',
            field=models.ForeignKey(blank=True, db_column='Entered by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entryperson', to='backend.e1people'),
        ),
        migrations.AlterField(
            model_name='r2participants',
            name='person',
            field=models.ForeignKey(blank=True, db_column='PersonID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='backend.e1people', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='r2participants',
            name='placeholder',
            field=models.ForeignKey(blank=True, db_column='Placeholder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.userplaceholders'),
        ),
    ]
