# Generated by Django 5.0.3 on 2024-08-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_e4groups_centre_e5centres_acronym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e5centres',
            name='acronym',
            field=models.CharField(blank=True, db_column='CentreAcronym', default='', max_length=50, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='e5centres',
            name='city',
            field=models.ForeignKey(blank=True, db_column='City', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e6cities', verbose_name='City'),
        ),
    ]
