# Generated by Django 5.0.3 on 2024-08-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_e5centres_acronym_alter_e5centres_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e4groups',
            name='centre',
            field=models.ForeignKey(blank=True, db_column='Centre', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres', verbose_name='Centre'),
        ),
    ]
