# Generated by Django 5.0.3 on 2024-11-25 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_userplaceholders_r2participants_entrydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r2participants',
            name='entrydate',
            field=models.DateTimeField(blank=True, db_column='Entry Date', default=django.utils.timezone.now),
        ),
    ]
