# Generated by Django 5.0.3 on 2024-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_r2participants_entrydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r2participants',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='r2participants',
            name='entrydate',
        ),
        migrations.RemoveField(
            model_name='r2participants',
            name='entryperson',
        ),
        migrations.DeleteModel(
            name='UserPlaceholders',
        ),
    ]
