# Generated by Django 5.0.3 on 2024-08-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_e4groups_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2activities',
            name='activity',
            field=models.CharField(blank=True, db_column='Activity', default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='description',
            field=models.TextField(blank=True, db_column='ActivityDescription', default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='e5centres',
            name='acronym',
            field=models.CharField(db_column='CentreAcronym', default='', max_length=50, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='e5centres',
            name='city',
            field=models.ForeignKey(db_column='City', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e6cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='r4groupassign',
            name='group',
            field=models.ForeignKey(db_column='GroupID', on_delete=django.db.models.deletion.CASCADE, to='backend.e4groups'),
        ),
        migrations.AlterField(
            model_name='r4groupassign',
            name='person',
            field=models.ForeignKey(db_column='PersonID', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.e1people'),
        ),
    ]
