# Generated by Django 5.0.3 on 2024-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_e2activities_activity_alter_e2activities_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e2activities',
            name='activity',
        ),
        migrations.AddField(
            model_name='e2activities',
            name='activityname',
            field=models.CharField(blank=True, db_column='ActivityName', default='', max_length=50, null=True),
        ),
    ]
