# Generated by Django 5.0.3 on 2024-11-25 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

CREATE_SQL_activity = """
DROP VIEW IF EXISTS activity_summary;
"""
DROP_SQL_activity = "DROP VIEW IF EXISTS activity_summary;"

CREATE_SQL_participant = """
DROP VIEW IF EXISTS participant_summary;

"""
DROP_SQL_participant = "DROP VIEW IF EXISTS participant_summary;"


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_activitysummary_participantsummary_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL_activity,
            reverse_sql=DROP_SQL_activity,
        ),
        migrations.RunSQL(
            sql=CREATE_SQL_participant,
            reverse_sql=DROP_SQL_participant,
        ),
        migrations.CreateModel(
            name='UserPlaceholders',
            fields=[
                ('placeholderid', models.AutoField(db_column='ParticipantsID', primary_key=True, serialize=False)),
                ('tempid', models.IntegerField(blank=True, db_column='TempID', null=True)),
                ('surname', models.CharField(blank=True, db_column='Surname', max_length=30, null=True, verbose_name='Surname')),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=30, null=True, verbose_name='First name')),
                ('othername', models.CharField(blank=True, db_column='OtherName', max_length=30, null=True, verbose_name='Other name(s)')),
            ],
            options={
                'verbose_name': 'User Placeholder',
            },
        ),
        migrations.AddField(
            model_name='r2participants',
            name='entrydate',
            field=models.DateTimeField(blank=True, db_column='Entry Date', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='r2participants',
            name='entryperson',
            field=models.ForeignKey(blank=True, db_column='Entered by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entryperson', to='backend.e1people'),
        ),
        migrations.AddField(
            model_name='r2participants',
            name='placeholder',
            field=models.ForeignKey(blank=True, db_column='Placeholder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.userplaceholders'),
        ),
        
    ]
