# Generated by Django 5.0.3 on 2024-09-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_e2activities_activityname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e1people',
            name='centre',
            field=models.ForeignKey(blank=True, db_column='Centre', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres', verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='activitytype',
            field=models.ForeignKey(db_column='ActivityTypeID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e2activitytype', verbose_name='Type of activity'),
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='centre',
            field=models.ForeignKey(blank=True, db_column='Centre', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e5centres', verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='person',
            field=models.ForeignKey(blank=True, db_column='PersonID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e1people', verbose_name='Person in charge'),
        ),
        migrations.AlterField(
            model_name='e4groups',
            name='centre',
            field=models.ForeignKey(blank=True, db_column='Centre', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.e5centres', verbose_name='Centre'),
        ),
    ]
