# Generated by Django 5.0.3 on 2024-11-25 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

CREATE_SQL_activity = """
DROP VIEW IF EXISTS activity_summary;
"""
DROP_SQL_activity = "DROP VIEW IF EXISTS activity_summary;"

CREATE_SQL_participant = """
DROP VIEW IF EXISTS participant_summary;

"""
DROP_SQL_participant = "DROP VIEW IF EXISTS participant_summary;"


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_activitysummary_participantsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL_activity,
            reverse_sql=DROP_SQL_activity,
        ),
        migrations.RunSQL(
            sql=CREATE_SQL_participant,
            reverse_sql=DROP_SQL_participant,
        ),
        migrations.RemoveField(
            model_name='r2participants',
            name='entryperson',
        ),
        migrations.AddField(
            model_name='r2participants',
            name='entryuser',
            field=models.ForeignKey(blank=True, db_column='EnteredBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Entered by'),
        ),
        migrations.AlterField(
            model_name='r2participants',
            name='placeholder',
            field=models.ForeignKey(blank=True, db_column='Placeholder', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.userplaceholders'),
        ),
    ]
