# Generated by Django 5.0.3 on 2024-09-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_e1people_centre_alter_e2activities_activitytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r1activitieslog',
            name='activity',
            field=models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.e2activities', verbose_name='Activity'),
        ),
    ]
