# Generated by Django 5.0.3 on 2024-11-25 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_activitysummary_participantsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r2participants',
            name='entrydate',
            field=models.DateTimeField(blank=True, db_column='EntryDate', default=django.utils.timezone.now),
        ),
    ]
