# Generated by Django 5.0.3 on 2024-09-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_r1activitieslog_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r8activitycentreassign',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='r8activitycentreassign',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='r9groupcentreassign',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='r9groupcentreassign',
            name='group',
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='person',
            field=models.ForeignKey(blank=True, db_column='PersonID', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.e1people', verbose_name='Person in charge'),
        ),
        migrations.AlterField(
            model_name='r2participants',
            name='activitieslogid',
            field=models.ForeignKey(db_column='ActivitiesLogID', default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.r1activitieslog', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='r2participants',
            name='person',
            field=models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='backend.e1people', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='r3categoryassign',
            name='person',
            field=models.ForeignKey(db_column='PersonID', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.e1people'),
        ),
        migrations.AlterField(
            model_name='r5attendedbyassign',
            name='person',
            field=models.ForeignKey(db_column='Person', on_delete=django.db.models.deletion.CASCADE, related_name='person', to='backend.e1people'),
        ),
        migrations.AlterField(
            model_name='r6activityassign',
            name='member',
            field=models.ForeignKey(blank=True, db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='backend.e1people'),
        ),
        migrations.DeleteModel(
            name='R7PersonCentreAssign',
        ),
        migrations.DeleteModel(
            name='R8ActivityCentreAssign',
        ),
        migrations.DeleteModel(
            name='R9GroupCentreAssign',
        ),
    ]
