# Generated by Django 5.0.3 on 2024-09-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_r8activitycentreassign_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r3categoryassign',
            options={'verbose_name': 'category (status)', 'verbose_name_plural': 'Categories (Status)'},
        ),
        migrations.AlterField(
            model_name='e1people',
            name='centre',
            field=models.ForeignKey(blank=True, db_column='Centre', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.e5centres', verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='activitytype',
            field=models.ForeignKey(db_column='ActivityTypeID', default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.e2activitytype', verbose_name='Type of activity'),
        ),
        migrations.AlterField(
            model_name='e2activities',
            name='centre',
            field=models.ForeignKey(blank=True, db_column='Centre', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.e5centres', verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='e5centres',
            name='city',
            field=models.ForeignKey(db_column='City', default='', on_delete=django.db.models.deletion.CASCADE, to='backend.e6cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='r1activitieslog',
            name='activity',
            field=models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.CASCADE, to='backend.e2activities', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='r3categoryassign',
            name='category',
            field=models.ForeignKey(db_column='CategoryID', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.e3categories'),
        ),
        migrations.AlterField(
            model_name='r5attendedbyassign',
            name='attendedby',
            field=models.ForeignKey(db_column='AttendedBy', on_delete=django.db.models.deletion.CASCADE, related_name='attendedby', to='backend.e1people'),
        ),
        migrations.AlterField(
            model_name='r6activityassign',
            name='activity',
            field=models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.CASCADE, to='backend.e2activities'),
        ),
    ]
