# Generated by Django 5.0.3 on 2024-11-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_r2participants_entrydate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userplaceholders',
            unique_together={('surname', 'firstname', 'othername')},
        ),
        migrations.AlterField(
            model_name='userplaceholders',
            name='firstname',
            field=models.CharField(db_column='FirstName', max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='userplaceholders',
            name='surname',
            field=models.CharField(db_column='Surname', max_length=30, verbose_name='Surname'),
        ),
        migrations.RemoveField(
            model_name='userplaceholders',
            name='tempid',
        ),
    ]
