# Generated by Django 5.0.3 on 2024-11-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_userplaceholders_tempid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaceholders',
            name='surname',
            field=models.CharField(db_column='Surname', max_length=30, verbose_name='Surname'),
        ),
    ]
