# Generated by Django 5.0.3 on 2024-11-27 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

CREATE_SQL_activity = """
DROP VIEW IF EXISTS activity_summary;
"""
DROP_SQL_activity = "DROP VIEW IF EXISTS activity_summary;"

CREATE_SQL_participant = """
DROP VIEW IF EXISTS participant_summary;

"""
DROP_SQL_participant = "DROP VIEW IF EXISTS participant_summary;"


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_userplaceholders_surname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL_activity,
            reverse_sql=DROP_SQL_activity,
        ),
        migrations.RunSQL(
            sql=CREATE_SQL_participant,
            reverse_sql=DROP_SQL_participant,
        ),
        migrations.AlterUniqueTogether(
            name='r2participants',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='r2participants',
            name='person',
            field=models.ForeignKey(blank=True, db_column='PersonID', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.e1people', verbose_name='Person'),
        ),
        migrations.AddConstraint(
            model_name='r2participants',
            constraint=models.UniqueConstraint(fields=('activitieslogid', 'person'), name='unique_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='r2participants',
            constraint=models.UniqueConstraint(condition=models.Q(('person', None)), fields=('activitieslogid',), name='unique_without_optional'),
        ),
    ]
