# Generated by Django 5.0.3 on 2024-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_activitysummary_participantsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5centres',
            name='external',
            field=models.CharField(db_column='ExternalName', default='', max_length=50, verbose_name='External name'),
        ),
    ]
