# Generated by Django 5.0.3 on 2024-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_e5centres_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e5centres',
            name='external',
            field=models.CharField(blank=True, db_column='CentreExternal', default='', max_length=50, null=True, verbose_name='External name'),
        ),
    ]
