# Generated by Django 5.0.3 on 2024-12-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_e5centres_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e5centres',
            name='external',
        ),
    ]
