# Generated by Django 5.0.3 on 2024-12-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_e5centres_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e5centres',
            name='external',
        ),
        migrations.AlterField(
            model_name='e1people',
            name='othername',
            field=models.CharField(blank=True, db_column='OtherName', default='', max_length=30, null=True, verbose_name='Other name(s)'),
        ),
        migrations.AddConstraint(
            model_name='e1people',
            constraint=models.UniqueConstraint(fields=('surname', 'firstname', 'othername'), name='unique_names'),
        ),
        migrations.AddConstraint(
            model_name='e1people',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
