# Generated by Django 5.0.3 on 2024-12-09 08:21

from django.db import migrations, models

CREATE_SQL_activity = """
DROP VIEW IF EXISTS activity_summary;
"""
DROP_SQL_activity = "DROP VIEW IF EXISTS activity_summary;"

CREATE_SQL_participant = """
DROP VIEW IF EXISTS participant_summary;

"""
DROP_SQL_participant = "DROP VIEW IF EXISTS participant_summary;"

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_activitysummary_participantsummary_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL_activity,
            reverse_sql=DROP_SQL_activity,
        ),
        migrations.RunSQL(
            sql=CREATE_SQL_participant,
            reverse_sql=DROP_SQL_participant,
        ),
        migrations.AlterField(
            model_name='r1activitieslog',
            name='activitydate',
            field=models.DateTimeField(db_column='ActivityDate', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='r1activitieslog',
            name='activityenddate',
            field=models.DateTimeField(blank=True, db_column='ActivityEndDate', null=True, verbose_name='End Date'),
        ),
    ]
