# Generated by Django 5.0.3 on 2024-12-12 09:25

import django.db.models.deletion
from django.db import migrations, models

CREATE_SQL_activity = """
DROP VIEW IF EXISTS activity_summary;
"""
DROP_SQL_activity = "DROP VIEW IF EXISTS activity_summary;"

CREATE_SQL_participant = """
DROP VIEW IF EXISTS participant_summary;

"""
DROP_SQL_participant = "DROP VIEW IF EXISTS participant_summary;"


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_activitysummary_participantsummary'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL_activity,
            reverse_sql=DROP_SQL_activity,
        ),
        migrations.RunSQL(
            sql=CREATE_SQL_participant,
            reverse_sql=DROP_SQL_participant,
        ),
        
    ]
