# Generated by Django 5.0.3 on 2024-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_activitysummary_participantsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('summaryid', models.AutoField(db_column='SummaryID', primary_key=True, serialize=False)),
                ('eventid', models.IntegerField(blank=True, db_column='EventID', null=True)),
                ('activitydate', models.DateField(blank=True, db_column='ActivityDate', null=True)),
                ('activityenddate', models.DateField(blank=True, db_column='ActivityEndDate', null=True)),
                ('activityid', models.IntegerField(blank=True, db_column='ActivityID', null=True)),
                ('activityname', models.CharField(blank=True, db_column='ActivityName', max_length=50, null=True)),
                ('activitycentre', models.CharField(blank=True, db_column='ActivityCentre', max_length=50, null=True)),
                ('activitytype', models.CharField(blank=True, db_column='ActivityType', max_length=15, null=True)),
                ('activitytypename', models.CharField(blank=True, db_column='ActivityTypeName', max_length=100, null=True)),
                ('participantid', models.IntegerField(blank=True, db_column='ParticipantID', null=True)),
                ('participanttype', models.TextField(blank=True, db_column='ParticipantType', null=True)),
                ('participantname', models.TextField(blank=True, db_column='ParticipantName', null=True)),
                ('participantcategory', models.CharField(blank=True, db_column='ParticipantCategory', max_length=6, null=True)),
                ('participantcentre', models.CharField(blank=True, db_column='ParticipantCentre', max_length=50, null=True)),
                ('participantgroup', models.CharField(blank=True, db_column='ParticipantGroup', max_length=50, null=True)),
            ],
            options={
                'db_table': 'activity_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantSummary',
            fields=[
                ('summaryid', models.AutoField(db_column='SummaryID', primary_key=True, serialize=False)),
                ('participantid', models.IntegerField(blank=True, db_column='ParticipantID', null=True)),
                ('participantname', models.TextField(blank=True, db_column='ParticipantName', null=True)),
                ('participantcategory', models.CharField(blank=True, db_column='ParticipantCategory', max_length=6, null=True)),
                ('participantcentre', models.CharField(blank=True, db_column='ParticipantCentre', max_length=50, null=True)),
                ('participantgroup', models.CharField(blank=True, db_column='ParticipantGroup', max_length=50, null=True)),
                ('participantfriendid', models.IntegerField(blank=True, db_column='ParticipantFriendID', null=True)),
                ('participantfriendname', models.TextField(blank=True, db_column='ParticipantFriendName', null=True)),
            ],
            options={
                'db_table': 'participant_summary',
                'managed': False,
            },
        ),
    ]
