# Generated by Django 5.0.3 on 2024-12-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_activitysummary_participantsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivitySummary',
        ),
        migrations.DeleteModel(
            name='ParticipantSummary',
        ),
    ]
