# Generated by Django 5.0.3 on 2024-12-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_alter_r2participants_placeholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r2participants',
            name='placeholder',
            field=models.ForeignKey(blank=True, db_column='PlaceholderID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.userplaceholders'),
        ),
        migrations.AlterField(
            model_name='userplaceholders',
            name='placeholderid',
            field=models.AutoField(db_column='PlaceholderID', primary_key=True, serialize=False),
        ),
    ]
