# Generated by Django 5.0.3 on 2024-12-16 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_activitysummary_participantsummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e1people',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=150, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
        ),
    ]
