# Generated by Django 5.0.3 on 2024-12-24 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_activitysummary_participantsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e1people',
            name='email',
            field=models.EmailField(db_column='Email', max_length=150, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
        ),
    ]
